In [29]:
from datamanager import read_data

In [60]:
import numpy as np

In [62]:
np.set_printoptions(suppress=True)

In [30]:
traindf, testdf = read_data()

In [31]:
traindf.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [32]:
testdf.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       8  ...       103        87        56         0         0         0   
1       0  ...        34         0         0         0         0         0   
2      99  ...         0         0         0         0        63        53   
3       0  ...       137       126       140         0       133       224   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2        31         0         0         0  
3       222        56         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [33]:
Xtrain = traindf.values

In [34]:
Xtrain

array([[2, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       ...,
       [8, 0, 0, ..., 0, 0, 0],
       [8, 0, 0, ..., 0, 0, 0],
       [7, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
Xtrain = Xtrain/255

In [ ]:
printmyname

In [ ]:
import numpy as np
w = np.random.uniform(-0.5, 0.5, (784,))

In [ ]:
w

In [ ]:
sign(-5)

In [ ]:
np.sign(-5)

In [ ]:
np.sign(+1)

In [ ]:
w

In [ ]:
x = np.random.uniform(0,1, (784,))

In [ ]:
np.dot(w,x)

In [ ]:
np.sign(np.dot(w,x))

In [ ]:
np.sum(w*x)

In [ ]:
np.dot(w,x)

In [ ]:
np.dot(x,x)

In [ ]:
np.linalg.norm(x)**2

In [ ]:
import math

In [ ]:
round(52.224,2)

In [ ]:
number = 7.34523421
f = '{0:.3g}'.format(number)
print(f)

In [38]:
train = traindf.values

In [50]:
Ytrain = Xtrain[:,0].astype(int)

In [51]:
Ytrain.shape

(60000,)

In [52]:
Ytrain[:5]

array([2, 9, 6, 0, 3])

In [53]:
w = np.random.uniform(-0.5, 0.5, (10,784))

In [54]:
x.shape

(784,)

In [55]:
F = np.zeros((10,784))

In [56]:
y = 5

In [57]:
F[y] = x

In [58]:
F

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [64]:
F[4]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [65]:
temp = w*F

In [66]:
temp.shape

(10, 784)

In [67]:
temp

array([[ 0., -0., -0., ..., -0.,  0.,  0.],
       [-0., -0., -0., ..., -0.,  0.,  0.],
       [ 0., -0.,  0., ...,  0.,  0., -0.],
       ...,
       [ 0.,  0.,  0., ..., -0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0., -0.,  0.],
       [ 0.,  0., -0., ..., -0.,  0., -0.]])

In [69]:
temp[0]

array([ 0., -0., -0.,  0.,  0., -0.,  0.,  0.,  0., -0., -0., -0., -0.,
        0.,  0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0.,  0.,  0.,
       -0., -0., -0., -0., -0., -0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,
       -0., -0., -0.,  0., -0.,  0.,  0.,  0., -0., -0., -0.,  0.,  0.,
        0.,  0.,  0., -0.,  0., -0.,  0.,  0., -0.,  0., -0.,  0., -0.,
       -0.,  0., -0., -0.,  0.,  0.,  0.,  0., -0.,  0., -0.,  0., -0.,
       -0., -0., -0.,  0., -0., -0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
        0., -0., -0.,  0.,  0.,  0.,  0.,  0., -0., -0., -0.,  0.,  0.,
       -0.,  0., -0., -0.,  0., -0.,  0.,  0., -0., -0.,  0.,  0.,  0.,
       -0., -0., -0., -0., -0., -0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,
        0.,  0.,  0.,  0.,  0., -0.,  0., -0., -0.,  0., -0.,  0., -0.,
       -0., -0., -0., -0., -0., -0.,  0.,  0., -0.,  0., -0.,  0.,  0.,
       -0., -0.,  0.,  0., -0., -0.,  0., -0.,  0., -0.,  0.,  0., -0.,
        0.,  0.,  0., -0.,  0.,  0.,  0., -0., -0.,  0., -0., -0

In [117]:
temp = np.sum(np.dot(w,np.transpose(F)))

In [118]:
#temp = np.dot(np.transpose(w), F)

In [119]:
temp.shape

()

In [120]:
temp

12.947259607674601

In [80]:
temp[1]

array([0.21585467, 0.12448903, 0.01240976, 0.21621325, 0.10199789,
       0.06049806, 0.16689619, 0.03979923, 0.15294645, 0.1115233 ,
       0.08917162, 0.16566116, 0.06854237, 0.16659811, 0.13248636,
       0.17101826, 0.00401428, 0.17590918, 0.22878084, 0.01012443,
       0.06969795, 0.18221769, 0.22876629, 0.13321714, 0.07456827,
       0.19621475, 0.04943315, 0.03202874, 0.12707629, 0.13500027,
       0.16449557, 0.14789425, 0.06745322, 0.02006449, 0.22277094,
       0.24216326, 0.21994947, 0.20216627, 0.01145399, 0.14364442,
       0.07699058, 0.04604152, 0.19141046, 0.08549041, 0.0243287 ,
       0.10875864, 0.18797879, 0.017029  , 0.23971676, 0.1906496 ,
       0.12555422, 0.24366943, 0.17467737, 0.10371553, 0.0821535 ,
       0.08733052, 0.13014848, 0.09019365, 0.02915841, 0.1811339 ,
       0.18638887, 0.20362505, 0.01984445, 0.0046088 , 0.11325637,
       0.203874  , 0.2325636 , 0.20219385, 0.09757036, 0.15188548,
       0.02694926, 0.23993243, 0.23301251, 0.12303444, 0.20154

In [81]:
np.sign(0)

0

In [76]:
np.sign(1)

1

In [112]:
tt = np.random.uniform(-3, 3, (5,5))

In [113]:
tt

array([[-2.14148304, -2.87229775, -0.51658783,  0.26591747,  1.42157868],
       [ 0.93959095,  2.8114595 ,  1.13970932, -1.38120675,  2.47889221],
       [-1.30138193, -0.56305707, -2.84753293,  1.74599199,  2.18907338],
       [-0.26869819, -0.18422714, -0.60927855,  2.03118529, -0.45174058],
       [-2.57773596, -2.34282822,  2.99250899, -2.77113715, -0.7939373 ]])

In [116]:
np.max(tt, axis=1)

array([1.42157868, 2.8114595 , 2.18907338, 2.03118529, 2.99250899])

In [123]:
for y in range(1,k):
    print(y)

1
2
3
4


In [122]:
k = 5

In [124]:
list(5)

TypeError: 'int' object is not iterable

In [126]:
x = [0]*5

In [127]:
x

[0, 0, 0, 0, 0]

In [128]:
x[1] = 5

In [129]:
x

[0, 5, 0, 0, 0]

In [130]:
np.argmax(x)

1